theme: jekyll-theme-merlot
# Site settings
title: Rewindding的小站-demo  				  	#你博客的标题
SEOTitle: Rewindding的little-site   	 #显示在浏览器上搜索的时候显示的标题


description: "You Blog"  			 #网站介绍
keyword: "" #关键词
url: "https://Rewindding.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
